[project]
name = "monthly-challenges"
version = "0.1.0"
description = "a monthly challenges web application"
authors = [
    {name = "Adam", email = "adamhimy19@gmail.com"},
]
dependencies = [
    "django==3.1.5",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

